use_frameworks!

platform :ios, '9.0'

target 'GCSUIViewCategory_Example' do
  pod 'GCSUIViewCategory', :path => '../'

  target 'GCSUIViewCategory_Tests' do
    inherit! :search_paths

    
  end
end
